FROM bensmithdeveloper/githubchart:latest AS builder
FROM bitnami/git:latest

ARG theme=default
ENV THEME=${theme}
ARG username
ENV USERNAME=${username}
ARG output_file=contribution.svg
ENV OUTPUT_FILE=${output_file}

ADD entrypoint.sh /
RUN chmod +x /entrypoint.sh
COPY --from=builder /usr/local/bundle/bin/githubchart /githubchart
ENTRYPOINT ["/entrypoint.sh"]