name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: bensmithdeveloper/githubchart
          username: bensmithdeveloper
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile